import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  // ─── Climatiseurs fixes ─────────────────────────────────
  {
    name: 'Daikin Stylish FTXM 9000 BTU',
    slug: 'daikin-stylish-ftxm-9000',
    type: 'climatiseur_fixe',
    brand: 'Daikin',
    model: 'FTXM35M',
    description: 'Climatiseur fixe Daikin Stylish avec design élégant et incurvé. Silencieux, performant et connecté.',
    technicalDescription: 'Technologie Inverter • Réfrigérant R32 • Compresseur scroll • Filtre photocatalytique • Télécommande • Minuterie 24h • Auto-diagnostic',
    price: 2499,
    salePrice: 2199,
    btu: '9000',
    surface: '25-35',
    noiseLevel: 19,
    energyClass: 'A+++',
    cop: 4.6,
    seer: 7.1,
    scop: 4.2,
    color: 'Blanc',
    dimensions: '78.5 × 29.5 × 26.0 cm',
    warranty: '5 ans',
    stock: 12,
    status: 'available',
    featured: true,
  },
  {
    name: 'Mitsubishi MSZ-LN 12000 BTU',
    slug: 'mitsubishi-msz-ln-12000',
    type: 'climatiseur_fixe',
    brand: 'Mitsubishi',
    model: 'MSZ-LN35VG',
    description: 'Climatiseur fixe Mitsubishi haut de gamme avec filtration plasma et WiFi intégré.',
    technicalDescription: 'Technologie Inverter • Filtration plasma • WiFi intégré • Réfrigérant R32 • Télécommande • Détecteur de mouvement 3D i-See',
    price: 2890,
    btu: '12000',
    surface: '30-45',
    noiseLevel: 22,
    energyClass: 'A+++',
    cop: 4.8,
    seer: 8.5,
    scop: 4.5,
    color: 'Blanc',
    dimensions: '83.0 × 30.0 × 25.0 cm',
    warranty: '5 ans',
    stock: 8,
    status: 'available',
    featured: true,
  },
  {
    name: 'LG Art Cool 18000 BTU',
    slug: 'lg-art-cool-18000',
    type: 'climatiseur_fixe',
    brand: 'LG',
    model: 'AP182R9DMA',
    description: 'Climatiseur LG Art Cool avec panneau design miroir, WiFi et détecteur de mouvement.',
    technicalDescription: 'Technologie Inverter • Panneau miroir • WiFi intégré • Détecteur de mouvement • Mode silence • Auto-nettoyage',
    price: 3299,
    btu: '18000',
    surface: '45-60',
    noiseLevel: 24,
    energyClass: 'A++',
    cop: 4.3,
    seer: 6.8,
    scop: 4.0,
    color: 'Blanc miroir',
    dimensions: '99.0 × 34.0 × 28.0 cm',
    warranty: '3 ans',
    stock: 5,
    status: 'available',
    featured: true,
  },
  {
    name: 'Hitachi RAC 24000 BTU',
    slug: 'hitachi-rac-24000',
    type: 'climatiseur_fixe',
    brand: 'Hitachi',
    model: 'RAC-WX25PA',
    description: 'Climatiseur Hitachi puissant pour grands espaces. Idéal pour commerces et grandes pièces.',
    technicalDescription: 'Compresseur rotatif • Réfrigérant R410A • Filtre désodorisant • Télécommande • Minuterie 24h • Débit d\'air puissant',
    price: 4199,
    btu: '24000',
    surface: '60-80',
    noiseLevel: 28,
    energyClass: 'A+',
    cop: 3.9,
    seer: 6.2,
    scop: 3.8,
    color: 'Blanc',
    dimensions: '110.0 × 38.5 × 30.0 cm',
    warranty: '3 ans',
    stock: 3,
    status: 'available',
    featured: false,
  },
  {
    name: 'Airconfort Eco Split 9000 BTU',
    slug: 'airconfort-eco-split-9000',
    type: 'climatiseur_fixe',
    brand: 'Airconfort',
    model: 'ACH-S09',
    description: 'Climatiseur split économique avec installation incluse. Excellent rapport qualité-prix.',
    technicalDescription: 'Technologie Inverter • Réfrigérant R32 • Filtre antibactérien • Télécommande • Mode nuit • Installation incluse',
    price: 1299,
    salePrice: 999,
    btu: '9000',
    surface: '20-30',
    noiseLevel: 22,
    energyClass: 'A+',
    cop: 3.8,
    seer: 6.0,
    scop: 3.6,
    color: 'Blanc',
    dimensions: '72.0 × 26.0 × 20.0 cm',
    warranty: '2 ans',
    stock: 20,
    status: 'available',
    featured: true,
  },
  {
    name: 'Samsung Wind Free 12000 BTU',
    slug: 'samsung-wind-free-12000',
    type: 'climatiseur_fixe',
    brand: 'Samsung',
    model: 'AR12TXCAAWKN',
    description: 'Technologie Wind Free sans courant d\'air direct. Idéal pour chambres et salons.',
    technicalDescription: 'Wind Free™ • Digital Inverter • WiFi intégré • Filtre Tri-Care • Mode silence • Auto Clean',
    price: 2799,
    salePrice: 2499,
    btu: '12000',
    surface: '30-40',
    noiseLevel: 18,
    energyClass: 'A+++',
    cop: 4.7,
    seer: 7.8,
    scop: 4.3,
    color: 'Blanc',
    dimensions: '82.0 × 30.0 × 22.0 cm',
    warranty: '5 ans',
    stock: 7,
    status: 'available',
    featured: true,
  },
  // ─── Climatiseurs mobiles ────────────────────────────────
  {
    name: 'Midea Mobily 12000 BTU',
    slug: 'midea-mobily-12000',
    type: 'climatiseur_mobile',
    brand: 'Midea',
    model: 'MPD-12CRN7',
    description: 'Climatiseur mobile 3-en-1 : froid, ventilation et déshumidification. Télécommande incluse.',
    technicalDescription: '3-en-1 (froid/ventilation/déshumidification) • Télécommande • Roulettes • Réservoir auto-évaporation • Minuterie',
    price: 599,
    salePrice: 499,
    btu: '12000',
    surface: '25-35',
    noiseLevel: 45,
    energyClass: 'A',
    cop: 2.9,
    color: 'Blanc',
    weight: 28.5,
    dimensions: '46.0 × 77.0 × 38.0 cm',
    warranty: '2 ans',
    stock: 30,
    status: 'available',
    featured: true,
  },
  {
    name: 'Airconfort Mobile Pro 10000 BTU',
    slug: 'airconfort-mobile-pro-10000',
    type: 'climatiseur_mobile',
    brand: 'Airconfort',
    model: 'ACH-MP10',
    description: 'Climatiseur mobile puissant et silencieux. Évacuation par fenêtre incluse.',
    technicalDescription: 'Froid/ventilation/déshumidification • Télécommande • Kit évacuation inclus • Roulettes • Minuterie 24h',
    price: 449,
    btu: '10000',
    surface: '20-30',
    noiseLevel: 42,
    energyClass: 'A',
    cop: 2.8,
    color: 'Blanc',
    weight: 25.0,
    dimensions: '44.0 × 72.0 × 36.0 cm',
    warranty: '2 ans',
    stock: 25,
    status: 'available',
    featured: true,
  },
  {
    name: 'LG PuriCare 14000 BTU',
    slug: 'lg-puricare-14000',
    type: 'climatiseur_mobile',
    brand: 'LG',
    model: 'LP1419IVSM',
    description: 'Climatiseur mobile LG avec inverter et purification d\'air intégrée. Ultra silencieux.',
    technicalDescription: 'Inverter • Purification d\'air • WiFi intégré • Contrôle vocal • Mode silence • Auto Clean',
    price: 899,
    btu: '14000',
    surface: '30-40',
    noiseLevel: 39,
    energyClass: 'A+',
    cop: 3.1,
    color: 'Blanc',
    weight: 32.0,
    dimensions: '50.0 × 81.0 × 41.0 cm',
    warranty: '2 ans',
    stock: 10,
    status: 'available',
    featured: false,
  },
  {
    name: 'Toshiba PAC 9000 BTU',
    slug: 'toshiba-pac-9000',
    type: 'climatiseur_mobile',
    brand: 'Toshiba',
    model: 'RAC-P09',
    description: 'Climatiseur mobile compact et léger, parfait pour petits espaces et location.',
    technicalDescription: 'Compact et léger • Télécommande • Kit fenêtre inclus • Déshumidification • Minuterie 24h',
    price: 399,
    btu: '9000',
    surface: '18-25',
    noiseLevel: 44,
    energyClass: 'A',
    cop: 2.7,
    color: 'Blanc',
    weight: 22.0,
    dimensions: '42.0 × 68.0 × 35.0 cm',
    warranty: '2 ans',
    stock: 18,
    status: 'available',
    featured: false,
  },
  {
    name: 'Midea Dual 16000 BTU',
    slug: 'midea-dual-16000',
    type: 'climatiseur_mobile',
    brand: 'Midea',
    model: 'MPD-16CRN7',
    description: 'Climatiseur mobile double évacuation pour une meilleure efficacité. Idéal pour grandes pièces.',
    technicalDescription: 'Double évacuation • Télécommande • Roulettes • Déshumidification • Réservoir auto-évaporation',
    price: 749,
    salePrice: 679,
    btu: '16000',
    surface: '35-50',
    noiseLevel: 47,
    energyClass: 'A',
    cop: 3.0,
    color: 'Blanc',
    weight: 33.5,
    dimensions: '48.0 × 82.0 × 40.0 cm',
    warranty: '2 ans',
    stock: 12,
    status: 'available',
    featured: true,
  },
  // ─── Ventilateurs ──────────────────────────────────────────
  {
    name: 'Dyson Pure Cool Link TP04',
    slug: 'dyson-pure-cool-tp04',
    type: 'ventilateur',
    brand: 'Dyson',
    model: 'TP04',
    description: 'Purificateur d\'air et ventilateur Dyson. Filtration HEPA, connecté WiFi, silencieux.',
    technicalDescription: 'Filtration HEPA H13 • Capteur Air Quality • WiFi • Oscillation 360° • Mode nuit • Télécommande',
    price: 699,
    salePrice: 599,
    btu: null,
    surface: '30-50',
    noiseLevel: 28,
    energyClass: 'A',
    color: 'Blanc/Argent',
    weight: 5.5,
    dimensions: '22.0 × 105.0 × 22.0 cm',
    warranty: '2 ans',
    stock: 8,
    status: 'available',
    featured: true,
  },
  {
    name: 'Rowenta Turbo Silence Extreme',
    slug: 'rowenta-turbo-silence-extreme',
    type: 'ventilateur',
    brand: 'Rowenta',
    model: 'VU5670',
    description: 'Ventilateur sur pied ultra puissant et silencieux. 5 vitesses, oscillation large, télécommande.',
    technicalDescription: 'Moteur Turbo Silence • 5 vitesses • Oscillation • Télécommande • Hauteur réglable • Grille safety-stop',
    price: 149,
    salePrice: 119,
    btu: null,
    surface: '20-35',
    noiseLevel: 32,
    energyClass: 'A',
    color: 'Noir',
    weight: 7.2,
    dimensions: '42.0 × 140.0 × 42.0 cm',
    warranty: '2 ans',
    stock: 45,
    status: 'available',
    featured: true,
  },
  {
    name: 'Dyson Air Multiplier AM07',
    slug: 'dyson-air-multiplier-am07',
    type: 'ventilateur',
    brand: 'Dyson',
    model: 'AM07',
    description: 'Ventilateur sans pales Dyson. Flux d\'air puissant et continu, sécurité enfant, télécommande.',
    technicalDescription: 'Technologie Air Multiplier™ • Pas de pales • Oscillation • Télécommande • Inclinaison • Sécurité enfants',
    price: 449,
    salePrice: 399,
    btu: null,
    surface: '20-30',
    noiseLevel: 30,
    energyClass: 'A',
    color: 'Blanc',
    weight: 4.2,
    dimensions: '23.0 × 100.0 × 23.0 cm',
    warranty: '2 ans',
    stock: 6,
    status: 'available',
    featured: true,
  },
  {
    name: 'Airconfort Ventilateur Colonne',
    slug: 'airconfort-ventilateur-colonne',
    type: 'ventilateur',
    brand: 'Airconfort',
    model: 'ACH-VC01',
    description: 'Ventilateur colonne silencieux avec télécommande, minuterie et oscillation. Design moderne.',
    technicalDescription: 'Silencieux • Télécommande • Minuterie 12h • Oscillation large • 3 vitesses • Design colonne moderne',
    price: 89,
    btu: null,
    surface: '15-25',
    noiseLevel: 35,
    energyClass: 'A',
    color: 'Blanc',
    weight: 5.0,
    dimensions: '30.0 × 90.0 × 30.0 cm',
    warranty: '1 an',
    stock: 60,
    status: 'available',
    featured: true,
  },
  {
    name: 'Airconfort Brumisateur Pro',
    slug: 'airconfort-brumisateur-pro',
    type: 'ventilateur',
    brand: 'Airconfort',
    model: 'ACH-VB02',
    description: 'Ventilateur brumisateur d\'extérieur. Parfait pour terrasses et jardins. Réservoir 5L.',
    technicalDescription: 'Brumisation fine • Réservoir 5L • Oscillation • 3 vitesses • Pompe haute pression • Roulettes',
    price: 129,
    btu: null,
    surface: '15-25',
    noiseLevel: 38,
    energyClass: 'A',
    color: 'Gris anthracite',
    weight: 6.5,
    dimensions: '38.0 × 85.0 × 38.0 cm',
    warranty: '1 an',
    stock: 22,
    status: 'available',
    featured: false,
  },
  {
    name: 'Rowenta Turbo Comfort',
    slug: 'rowenta-turbo-comfort',
    type: 'ventilateur',
    brand: 'Rowenta',
    model: 'VU5740',
    description: 'Ventilateur de table puissant. 4 pales, 3 vitesses, design compact.',
    technicalDescription: '4 pales • 3 vitesses • Oscillation • Poignée de transport • Grille amovible • Pied stable',
    price: 69,
    btu: null,
    surface: '10-20',
    noiseLevel: 36,
    energyClass: 'A',
    color: 'Blanc',
    weight: 3.8,
    dimensions: '35.0 × 50.0 × 35.0 cm',
    warranty: '2 ans',
    stock: 35,
    status: 'available',
    featured: false,
  },
  {
    name: 'Airconfort Ventilateur Plafond',
    slug: 'airconfort-ventilateur-plafond',
    type: 'ventilateur',
    brand: 'Airconfort',
    model: 'ACH-VP03',
    description: 'Ventilateur de plafond design avec télécommande et lumière LED intégrée.',
    technicalDescription: 'Moteur DC • Lumière LED intégrée • Télécommande • 6 vitesses • Minuterie • Montage facile',
    price: 179,
    btu: null,
    surface: '20-35',
    noiseLevel: 25,
    energyClass: 'A++',
    color: 'Blanc',
    weight: 8.0,
    dimensions: '132.0 × 42.0 cm (diam.)',
    warranty: '2 ans',
    stock: 15,
    status: 'available',
    featured: true,
  },
  {
    name: 'Midea Ventilateur Station',
    slug: 'midea-ventilateur-station',
    type: 'ventilateur',
    brand: 'Midea',
    model: 'MFS-40',
    description: 'Ventilateur station professionnel pour atelier et commerce. Débit d\'air puissant.',
    technicalDescription: 'Pales métal • Moteur cuivre • 3 vitesses • Oscillation • Grille sécurité • Pied réglable',
    price: 199,
    btu: null,
    surface: '30-60',
    noiseLevel: 42,
    energyClass: 'B',
    color: 'Noir',
    weight: 10.5,
    dimensions: '60.0 × 75.0 × 60.0 cm',
    warranty: '1 an',
    stock: 10,
    status: 'available',
    featured: false,
  },
  {
    name: 'LG PuriCare Mini',
    slug: 'lg-puricare-mini',
    type: 'ventilateur',
    brand: 'LG',
    model: 'AP320P',
    description: 'Purificateur ventilateur compact. Idéal pour bureau et petite chambre. Filtration triple.',
    technicalDescription: 'Filtration triple • HEPA H13 + Charbon • Mode auto • Compact • Ultra silencieux • Consommation faible',
    price: 249,
    salePrice: 199,
    btu: null,
    surface: '15-25',
    noiseLevel: 24,
    energyClass: 'A+',
    color: 'Blanc',
    weight: 3.2,
    dimensions: '35.0 × 55.0 × 20.0 cm',
    warranty: '2 ans',
    stock: 20,
    status: 'available',
    featured: false,
  },
  {
    name: 'Panasonic Ventilateur Silencieux',
    slug: 'panasonic-ventilateur-silencieux',
    type: 'ventilateur',
    brand: 'Panasonic',
    model: 'F-60S9',
    description: 'Ventilateur sur pied Panasonic ultra silencieux. Moteur DC, 8 vitesses, télécommande.',
    technicalDescription: 'Moteur DC • 8 vitesses • Télécommande • Oscillation • Minuterie 7h • Consommation 80% réduite',
    price: 169,
    btu: null,
    surface: '20-35',
    noiseLevel: 22,
    energyClass: 'A++',
    color: 'Noir',
    weight: 6.8,
    dimensions: '40.0 × 130.0 × 40.0 cm',
    warranty: '2 ans',
    stock: 14,
    status: 'available',
    featured: false,
  },
];

async function main() {
  console.log('🌱 Seed AIRCONFORTHABITAT...');

  // Clean existing data
  await prisma.orderTracking.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.customer.deleteMany();
  await prisma.stockAlert.deleteMany();
  await prisma.adminLog.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  // Create categories
  const categories = await Promise.all([
    prisma.category.create({ data: { name: 'Climatiseurs fixes', slug: 'climatiseurs-fixes', icon: '❄', sort: 1 } }),
    prisma.category.create({ data: { name: 'Climatiseurs mobiles', slug: 'climatiseurs-mobiles', icon: '🔄', sort: 2 } }),
    prisma.category.create({ data: { name: 'Ventilateurs', slug: 'ventilateurs', icon: '💨', sort: 3 } }),
  ]);

  // Create products
  for (let i = 0; i < products.length; i++) {
    const p = products[i];
    const catMap = {
      climatiseur_fixe: categories[0].id,
      climatiseur_mobile: categories[1].id,
      ventilateur: categories[2].id,
    };
    await prisma.product.create({
      data: {
        ...p,
        categoryId: catMap[p.type],
        price: p.price,
        imageUrl: `https://images.unsplash.com/photo-${i % 2 === 0 ? '1585771720169-19a4b0b8f9b1?w=600&q=80' : '1621905231877-8c1a6f8e3b9a?w=600&q=80'}`,
      },
    });
  }

  console.log(`✅ ${products.length} produits créés`);
  console.log('✅ Seed terminé !');
}

main()
  .catch(e => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
